# Generated by Django 5.2.7 on 2025-10-16 02:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('biographie', models.TextField(blank=True, verbose_name='Biographie')),
                ('annee_naissance', models.IntegerField(blank=True, null=True, verbose_name='Année de naissance')),
                ('annee_deces', models.IntegerField(blank=True, null=True, verbose_name='Année de décès')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='Nationalité')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='artistes/', verbose_name='Photo')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Artiste',
                'verbose_name_plural': 'Artistes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('icone', models.ImageField(blank=True, null=True, upload_to='categories/icones/', verbose_name='Icône')),
                ('couleur', models.CharField(default='#3B82F6', help_text='Couleur hexadécimale (ex: #FF5733)', max_length=7, verbose_name='Couleur')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage", verbose_name='Ordre')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('description_courte', models.CharField(blank=True, max_length=500, verbose_name='Description courte')),
                ('annee', models.IntegerField(blank=True, null=True, verbose_name='Année de création')),
                ('epoque', models.CharField(blank=True, max_length=100, verbose_name='Époque')),
                ('image_miniature', models.ImageField(upload_to='oeuvres/miniatures/', verbose_name='Image miniature')),
                ('image_haute_resolution', models.ImageField(blank=True, null=True, upload_to='oeuvres/hd/', verbose_name='Image haute résolution')),
                ('modele_3d', models.FileField(blank=True, help_text='Format .glb ou .gltf', null=True, upload_to='modeles_3d/', verbose_name='Modèle 3D')),
                ('audio_guide', models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='Guide audio')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Vidéo')),
                ('lien_video_externe', models.URLField(blank=True, help_text='Lien YouTube ou Vimeo', verbose_name='Lien vidéo externe')),
                ('position_x', models.FloatField(default=0, verbose_name='Position X')),
                ('position_y', models.FloatField(default=0, verbose_name='Position Y')),
                ('position_z', models.FloatField(default=0, verbose_name='Position Z')),
                ('rotation', models.FloatField(default=0, help_text='Rotation en degrés', verbose_name='Rotation')),
                ('echelle', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(10.0)], verbose_name='Échelle')),
                ('dimensions', models.CharField(blank=True, help_text='Ex: 120 x 80 cm', max_length=100, verbose_name='Dimensions')),
                ('technique', models.CharField(blank=True, max_length=200, verbose_name='Technique')),
                ('materiau', models.CharField(blank=True, max_length=200, verbose_name='Matériau')),
                ('collection', models.CharField(blank=True, max_length=200, verbose_name='Collection')),
                ('numero_inventaire', models.CharField(blank=True, max_length=50, unique=True, verbose_name="Numéro d'inventaire")),
                ('metadonnees', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('est_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('est_mise_en_avant', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('nombre_vues', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('artiste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oeuvres', to='core.artiste', verbose_name='Artiste')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oeuvres', to='core.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Œuvre',
                'verbose_name_plural': 'Œuvres',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('est_approuve', models.BooleanField(default=False, verbose_name='Approuvé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='core.oeuvre', verbose_name='Œuvre')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('largeur', models.FloatField(default=20.0, help_text='Largeur en mètres', verbose_name='Largeur')),
                ('longueur', models.FloatField(default=20.0, help_text='Longueur en mètres', verbose_name='Longueur')),
                ('hauteur', models.FloatField(default=4.0, help_text='Hauteur en mètres', verbose_name='Hauteur')),
                ('couleur_murs', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Couleur des murs')),
                ('texture_sol', models.ImageField(blank=True, null=True, upload_to='salles/textures/', verbose_name='Texture du sol')),
                ('eclairage', models.CharField(choices=[('naturel', 'Lumière naturelle'), ('chaud', 'Éclairage chaud'), ('froid', 'Éclairage froid'), ('tamisé', 'Éclairage tamisé')], default='naturel', max_length=50, verbose_name='Éclairage')),
                ('ordre', models.IntegerField(default=0, verbose_name='Ordre')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='core.categorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='salle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oeuvres', to='core.salle', verbose_name='Salle'),
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateTimeField(auto_now_add=True, verbose_name='Date de visite')),
                ('duree_secondes', models.IntegerField(default=0, verbose_name='Durée (secondes)')),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='core.oeuvre', verbose_name='Œuvre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date_visite'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('oeuvre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='core.oeuvre', verbose_name='Œuvre')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'oeuvre')},
            },
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(fields=['slug'], name='core_oeuvre_slug_7717e2_idx'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(fields=['categorie', 'est_visible'], name='core_oeuvre_categor_2aceb8_idx'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(fields=['-nombre_vues'], name='core_oeuvre_nombre__5e8789_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['utilisateur', '-date_visite'], name='core_visite_utilisa_9692da_idx'),
        ),
    ]
